---

- name: Push Package
  copy: src=../file/mysql5-6-26.tgz dest=/tmp/ owner=root group=root

- name: Create Mysql Datadir
  file: path={{ item }} state=directory #owner=mysql group=mysql
  with_items:
#  - /data/mysql
  - "{{ mysql_datadir }}"
  - "{{ mysql_master_bin_log }}"
#  register: result
# mysql 目录权限，appaor权限 
- name: appaorm
  copy: src=../file/usr.sbin.mysqld dest=/etc/apparmor.d/usr.sbin.mysqld owner=root group=root mode=644
#notify:
#  - restart apparmor
- name: restart apparmor
  service: name=apparmor state=restarted

- name: Extract Package
  shell: mkdir -p /tmp/mysql | tar xf /tmp/mysql5-6-26.tgz -C /tmp/mysql

- name: Install Mysql-common
  apt: deb={{ item }}
  with_items:
  - /tmp/mysql/libaio1_0.3.109-2ubuntu1_amd64.deb
  - /tmp/mysql/mysql-common_5.6.26-1ubuntu12.04_amd64.deb
- name: debconf mysql-community-server
  debconf: name=mysql-community-server_5.6.26-1ubuntu12.04_amd64.deb question={{ item.name }} value={{ item.var }} vtype={{ item.type }}
  with_items:
  - { name: "mysql-community-server/root-pass", var: "XimiMsat19292014", type: "password" }
  - { name: "mysql-community-server/re-root-pass", var: "XimiMsat19292014", type: "password" }
  - { name: "mysql-community-server/data-dir", var: "ok", type: "note"  }
- name: Install Mysql-community-server
  apt: deb=/tmp/mysql/mysql-community-server_5.6.26-1ubuntu12.04_amd64.deb
- name: Install Mysql-server
  apt: deb=/tmp/mysql/mysql-server_5.6.26-1ubuntu12.04_amd64.deb
- name: Install Mysql-community-client
  apt: deb=/tmp/mysql/mysql-community-client_5.6.26-1ubuntu12.04_amd64.deb
- name: Install Mysql-client
  apt: deb=/tmp/mysql/mysql-client_5.6.26-1ubuntu12.04_amd64.deb

- name: Stop mysql-server
  service: name=mysql state=stopped

- name: mv /var/lib/mysql/*
  shell: mv /var/lib/mysql/* /data/mysql/db/

- name: mysql priv
  shell: chown -R mysql:mysql /data/mysql

- name: Push Mysql Configure
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
#  when: result|success

- name: Delete Mysql Tempfile
  service: name=mysql state=started
  notify:
  - restart mysql
  - del mysql tempfile
#  - add user_dbaroot
#  - add user view
#  - add user ximislave
