---
- name: push package
  copy: src=../file/mongodb-3.0.6.tgz dest=/opt owner=root group=root
  #copy: src=../file/mongodb2-6.tgz des=/opt
- name: useradd mongodb zabbix
  shell: useradd mongodb #&& useradd zabbix
#- name: apt acl
#  apt: name={{ item }} state=present
#  with_items:
#  - acl
- name: Extract package
  shell: tar xf /opt/mongodb-3.0.6.tgz -C /opt && mv /opt/mongodb-linux-x86_64-ubuntu1204-3.0.6 /opt/mongodb
- name: env mongo
  shell: echo "PATH=$PATH:/opt/mongodb/bin" >> /etc/profile 
- name: env mongo1
  shell: echo "rs.slaveOk();" >> /root/.mongorc.js 
- name: env mongo2
  shell: . /etc/profile
- name: change Privilege
  file: path=/opt/mongodb/bin owner=root group=root mode=754 
- name: mongo acl
#  acl: name=/opt/mongodb/bin/mongo entity=zabbix permissions=rx
  acl: name=/opt/mongodb/bin/mongo entity=zabbix etype=user permissions="rwx" state=present
- name: Create Mongo Datadir
  file: path={{ item }} state=directory
  with_items:
  - "{{ mongodb_log_dir }}"
  - "{{ mongo_datadir }}/{{ mongo_master_port }}"
  - "{{ mongo_config_dir }}"
  - "{{ mongo_backup_dir }}/{{ mongo_master_port }}"
  register: result
  ignore_errors: True
- name: push mongo_master configure
  template: src=mongodmaster.conf.j2 dest=/etc/mongodb/mongod.conf
#  when: "hosts == 'mongo_master'" 
  when: result|success and ansible_all_ipv4_addresses[0] == "192.168.7.80"
  notify: 
   - start mongodb
   - del mongo.tgz
- name: push mongo_slaver configure
  template: src=mongodslaver.conf.j2 dest=/etc/mongodb/mongod.conf
#  when: "hosts == 'mongo_slaver'"
  when: result|success and ansible_all_ipv4_addresses[0] == "192.168.7.96"
  notify:
   - start mongodb
   - del mongo.tgz
